import React from 'react';
import { Link } from 'react-router-dom';
import Header from '../components/Header';

function HomePage() {
  return (
    <div>
      <Header />
      
      <div className="hero">
        <div className="container">
          <h1 className="hero-title">NAYAYVAULT</h1>
          <h2 className="hero-subtitle">Secure Digital Document Management System</h2>
          <h3 style={{ fontSize: '14px', color: '#8B7355', marginBottom: '30px' }}>For Legal, Investigation and Forensic Document Management</h3>
          <p className="hero-description">
            NAYAYVAULT provides a secure and centralized platform for managing sensitive legal, investigation, court, and forensic documents with controlled access, SHA-256 document integrity verification, tamper detection, version control, and complete auditability.
          </p>
          <div className="hero-buttons">
            <Link to="/login" className="button button-primary">Secure Login</Link>
            <button className="button button-secondary">Learn More</button>
          </div>
        </div>
      </div>

      <div className="container" style={{ padding: '60px 20px' }}>
        <div style={{ textAlign: 'center', marginBottom: '50px' }}>
          <h2 style={{ fontSize: '32px', fontWeight: '700', color: '#1A1A2E', marginBottom: '15px' }}>Key Features</h2>
          <p style={{ fontSize: '16px', color: '#666' }}>NAYAYVAULT ensures document security through advanced cryptography and access control</p>
        </div>

        <div className="grid-2">
          <div className="feature-box">
            <div className="feature-icon">🔐</div>
            <div className="feature-title">Secure Access</div>
            <div className="feature-description">Role-based access ensures documents are accessible only to authorized users based on their role and case assignment.</div>
          </div>

          <div className="feature-box">
            <div className="feature-icon">🔒</div>
            <div className="feature-title">SHA-256 Document Integrity</div>
            <div className="feature-description">Every uploaded document receives a SHA-256 cryptographic fingerprint generated by the backend for tamper detection.</div>
          </div>

          <div className="feature-box">
            <div className="feature-icon">📁</div>
            <div className="feature-title">Centralized Management</div>
            <div className="feature-description">Securely organize and manage documents throughout the lifecycle of a case with version control.</div>
          </div>

          <div className="feature-box">
            <div className="feature-icon">📜</div>
            <div className="feature-title">Complete Auditability</div>
            <div className="feature-description">Maintain a traceable record of all important document and security activities in an append-only audit log.</div>
          </div>
        </div>
      </div>

      <div style={{ backgroundColor: '#f0f0f0', padding: '40px 20px', marginTop: '40px', borderTop: '3px solid #8B7355' }}>
        <div className="container">
          <div style={{ textAlign: 'center' }}>
            <h3 style={{ fontSize: '18px', fontWeight: '600', color: '#1A1A2E', marginBottom: '20px' }}>Supported Document Types</h3>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '15px', justifyContent: 'center', fontSize: '14px' }}>
              <span style={{ backgroundColor: 'white', padding: '8px 16px', borderRadius: '4px' }}>FIRs</span>
              <span style={{ backgroundColor: 'white', padding: '8px 16px', borderRadius: '4px' }}>Police Reports</span>
              <span style={{ backgroundColor: 'white', padding: '8px 16px', borderRadius: '4px' }}>Investigation Records</span>
              <span style={{ backgroundColor: 'white', padding: '8px 16px', borderRadius: '4px' }}>Witness Statements</span>
              <span style={{ backgroundColor: 'white', padding: '8px 16px', borderRadius: '4px' }}>Charge Sheets</span>
              <span style={{ backgroundColor: 'white', padding: '8px 16px', borderRadius: '4px' }}>Court Filings</span>
              <span style={{ backgroundColor: 'white', padding: '8px 16px', borderRadius: '4px' }}>Evidence Records</span>
              <span style={{ backgroundColor: 'white', padding: '8px 16px', borderRadius: '4px' }}>Forensic Reports</span>
              <span style={{ backgroundColor: 'white', padding: '8px 16px', borderRadius: '4px' }}>Court Judgments</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default HomePage;
